#!/bin/sh
### BEGIN INIT INFO
# Provides:          premailer
# Required-Start:    $local_fs $remote_fs $network $syslog
# Required-Stop:     $local_fs $remote_fs $network $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start/stop node servers batch script
### END INIT INFO

APP_HOME=/home/vanng822/src/premailer-demo
SUDO_AS_USER="sudo -H -u vanng822"
PID_FILE=$APP_HOME/premailer.pid
CMD=$APP_HOME/bin/premailer

cleanup_pid() {
        echo "clean up"
}

stop_server() {
	echo "Stop imgscale server"
	PID=$(cat $PID_FILE)
	$SUDO_AS_USER kill $PID > /dev/null 2>&1&
	echo "Imgscale server stopped!"
}

start_server() {
	echo "Start server"
    cd $APP_HOME
   	$SUDO_AS_USER god --pidfile $PID_FILE -s $CMD > /dev/null 2>&1&
   	echo "Server started"
}

reload_server() {
	echo "Reload server"
	PID=$(cat $PID_FILE)
	$SUDO_AS_USER kill -s USR2 $PID  > /dev/null 2>&1&
	echo "Server reloaded"
}

restart_server() {
	echo "Restart server"
	PID=$(cat $PID_FILE)
	$SUDO_AS_USER kill -s HUP $PID  > /dev/null 2>&1&
	echo "Restart server done"
}

case "$1" in
		force-restart)
			stop_server
			sleep 1
			start_server
			exit 0
			;;
		reload)
			reload_server
			exit 0
			;;
        start)
            start_server
            exit 0
             ;;
        stop)
        	stop_server
            exit 0
             ;;
        restart)
        	restart_server
        	exit 0
esac
